Writing chapter 1
vivliostyle/vivliostyle-cli-helper-doc pull request #1
Opened 2023-09-29 04:39 UTC by ogwata

ひとまず、1章まで書き終えたのでPRを出しました。
ご確認ください。

2023-10-01 03:33 UTC, MurakamiShinyu approved these changes
👍

2023-10-01 06:01 UTC, lwohtsu commented on ja/1-readme-first/about-this-document.md
@ogwata 
「煩雑な作業」というか「修得や理解に時間を要するもの」を省略したというのが近い気がします。
人によって、コマンドを正確にタイプする能力、テキスト指定が振る舞いに反映されることへの慣れ、CSSやHTMLの基礎知識など様々ですが。前者2つはいっても仕方がないことなので、「CSSやHTMLの基礎などを知っている前提でしばしば省略されている～」など？

2023-10-01 06:02 UTC, lwohtsu requested changes
1箇所コメント入れましたのでよろしくお願いします。

2023-10-01 13:56 UTC, ogwata commented on ja/1-readme-first/about-this-document.md
以下のように修正してみました。ご確認ください。

> ただしその反面、セミナーではCSSやHTMLの基礎などは既に知っている前提で、細かな作業の説明がしばしば省略されている。もしやこの点が、初めて使うユーザを混乱させないだろうか。

2023-10-03 03:12 UTC, lwohtsu requested changes
2章確認しました

2023-10-03 03:12 UTC, lwohtsu commented on ja/2-introduction-to-vivliostyle/3-how-to-use-vivliostyle-cil-helper.md
> +
ターミナルを表示する操作は不要です。
右クリックメニューからvivliostyle-cli-helperの操作を実行すると、自動的にターミナルが表示されます。

2023-10-03 03:12 UTC, lwohtsu commented on ja/2-introduction-to-vivliostyle/3-how-to-use-vivliostyle-cil-helper.md
> +
フォルダーを開く操作はすでにやっているのでしたっけ？　やっているのならOKですが、やらないとプレビューを表示できません（エラーになります）。

2023-10-03 03:13 UTC, lwohtsu commented on ja/1-readme-first/about-this-document.md
1章はこれでOKです

2023-10-03 04:19 UTC, ogwata commented on ja/2-introduction-to-vivliostyle/3-how-to-use-vivliostyle-cil-helper.md
> +
改訂しました。ごかくにん

2023-10-03 04:20 UTC, ogwata commented on ja/2-introduction-to-vivliostyle/3-how-to-use-vivliostyle-cil-helper.md
> +
ご指摘に答えてインストール部分をぜんめｎ

2023-10-03 04:29 UTC, ogwata commented on ja/2-introduction-to-vivliostyle/3-how-to-use-vivliostyle-cil-helper.md
> +
失礼しました！　たしかにフォルダを開く操作を説明していませんでした。追加したのでごかく

2023-10-03 07:42 UTC, lwohtsu commented on ja/2-introduction-to-vivliostyle/3-how-to-use-vivliostyle-cil-helper.md
> +
すみません、うまく改訂部分を確認できていないかもしれないのですが、
「フォルダーを開く操作」というのは、『CSS組版入門』P.39で説明している「ファイル」メニュー→「フォルダーを開く」を選択して、ダウンロードしたサンプルのフォルダを選ぶことです。
これがどこかに記述されていればOKなのですが……。

2023-10-03 08:15 UTC, ogwata commented on ja/2-introduction-to-vivliostyle/3-how-to-use-vivliostyle-cil-helper.md
> +
第1章の冒頭、第1節の中でフォルダを開いています。

2023-10-03 08:25 UTC, merged